version: '3.8'

services:
  app:
    image: 'klintonlee/simples-dental-desafio'
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - my_app

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: profissionais
    networks:
       - my_app

networks:
  my_app: