name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

env:
  IMAGE_NAME: klintonlee/simples-dental-desafio

jobs:
  build:
    name: Build runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK@17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build application
        run: mvn package
      - name: Log in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: klintonlee/simples-dental-desafio:latest